#!/usr/bin/python2.7

#    LineageOS Enthusiast's Security Kitchen
#    Copyright (C) 2017 Davis Mosenkovs
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see https://www.gnu.org/licenses/

import requests
import subprocess
import json

class colors:
  BLUE = '\033[94m'
  GREEN = '\033[92m'
  YELLOW = '\033[93m'
  RED = '\033[91m'
  ENDC = '\033[0m'


print colors.BLUE+"Checking state of CVE code review requests submitted to Gerrit..."+colors.ENDC

gerrit_user = subprocess.check_output("git config --global --get review.review.lineageos.org.username", shell=True).strip()
if gerrit_user=="":
  raise EnvironmentError("Git global setting review.review.lineageos.org.username not configured")

openreqstr = requests.get("https://review.lineageos.org/changes/?q=status:open+owner:"+gerrit_user+"&n=1000&o=MESSAGES&o=LABELS").content
assert(openreqstr.startswith(")]}'"))
openreqs = json.loads(openreqstr[4:])

cvereqs = filter(lambda r: 'topic' in r and r['topic'].upper().startswith("CVE-"), openreqs)
cves = {}

for r in cvereqs:
  if r['topic'] in cves:
    cves.update({r['topic']: cves[r['topic']]+1})
  else:
    cves.update({r['topic']: 1})
for i in sorted(cves, key=cves.get, reverse=True):
  print i+" has "+repr(cves[i])+" opened review requests"
print ""
print "Total opened CVE review requests: "+repr(len(cvereqs))
print ""

for r in cvereqs:
  displayed = False
  owner = r['owner']['_account_id']
  for m in r['messages']:
    if (m['author']['_account_id'] != owner) and (not 'tag' in m or m['tag'] != "autogenerated:gerrit:deleteReviewer"):
      if not displayed:
        print ""
        print colors.YELLOW+"https://review.lineageos.org/"+repr(r['_number'])+colors.ENDC
        displayed = True
      print m['message']
  if displayed:
    print ""
